### ISSUE TITLE
Webdriver error

### ISSUE THREAD

**Issue by bugula** [d-Raco/shopping-bot-framework#1]
Hi - not a programmer but anxious to test out your scripts. Have set up the environments and been playing with the scraping but when I run sbf, I receive the following error and can't figure out how to solve:

self.driver = webdriver.Firefox(options=opt, firefox_profile=profile)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'

Thanks for any help.

**Comment by d-Raco** [comment]
Hi, thanks for the warning! Indeed, the firefox_profile argument of the selenium wedbriver has been depracated, it should now be fixed :)

By the way, I should warn you that this is a personal project that unfortunately I haven't had time to continue developing, so there are some features that I would have loved to have added, but unfortunately couldn't... If it still meets your needs, I'm glad you find it useful :D
